# Generated by Django 3.2 on 2021-04-19 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='center',
            field=models.ManyToManyField(related_name='center_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
