# Generated by Django 3.2 on 2021-05-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_viewedlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
